### ISSUE TITLE
Few Shot is just One Shot here?

### ISSUE THREAD

**Issue by alexander-fischer** [ByChelsea/VAND-APRIL-GAN#15]
From debugging the code, it seems that here the patch tokens of just one reference image are compared to the query image since we iterate over `patch_tokens` that has the length of `few_shot_features`. Shouldn't it be possible to use multiple reference images with the `k_shot` variable?

https://github.com/ByChelsea/VAND-APRIL-GAN/blob/46fcbe567752dbcc84a26a05fb7b3794a72aa008/test.py#L189-L201

**Comment by ByChelsea** [comment]
Hi, the iteration over `patch_tokens` is carried out to individually compare the output features of the four blocks. In other words, we use a total of `few_shot_features` memory banks. During [data preparation](https://github.com/ByChelsea/VAND-APRIL-GAN/blob/46fcbe567752dbcc84a26a05fb7b3794a72aa008/dataset.py#L29), we employ the variable `k_shot`, and the names of the randomly selected reference images are recorded in `./results/mvtec/few_shot/4shot/seed42/k_shot.txt`.

**Comment by alexander-fischer** [comment]
You're right!
