### ISSUE TITLE
Is there a way to get the score of how anomalous an image is?

### ISSUE THREAD

**Issue by hnyll** [ByChelsea/VAND-APRIL-GAN#22]
I want to know if there is a variable/method i can use to score how suspicious/anomalous an image is. im kind of new to this stuff so idk lol

**Comment by ByChelsea** [comment]
Anomaly detection can be divided into two subtasks: anomaly classification and segmentation. The anomaly score (i.e. `results['pr_sp']` in the test.py) for classification is what you want. BTW, I recommend checking relevant papers before reviewing the code; it will greatly aid in understanding. :)

**Comment by hnyll** [comment]
tyty. i will def check out the relevant papers 👍
