### ISSUE TITLE
除了添加的线性层 clip其它部分的权重有被微调吗

### ISSUE THREAD

**Issue by TerryMelody** [ByChelsea/VAND-APRIL-GAN#29]
您好！请问在训练过程中，除了添加的线性层clip其它部分的权重有被微调吗？还是clip主干部分的权重是冻结的呢。

**Comment by ByChelsea** [comment]
Hi, except for the added linear layers, everything else was not fine-tuned.

**Comment by TerryMelody** [comment]
> Hi, except for the added linear layers, everything else was not fine-tuned.

Thanks a lot!
