### ISSUE TITLE
实验结果的可视化问题

### ISSUE THREAD

**Issue by archyin** [ByChelsea/VAND-APRIL-GAN#7]
跑了一下test，出来的结果是这样的，
![image](https://github.com/ByChelsea/VAND-APRIL-GAN/assets/13670653/4168296d-6045-4098-b303-b13e6a029e69)
有那种二值化的结果图，或者把异常区域圈出来的吗？

**Comment by ByChelsea** [comment]
Hi! You can binarize the anomaly map by selecting a threshold. I recommend using the optimal threshold obtained when calculating the F1-max score: 

`precisions, recalls, thresholds = precision_recall_curve(label, predict)
f1_scores = (2 * precisions * recalls) / (precisions + recalls)
f1_max = np.max(f1_scores[np.isfinite(f1_scores)])
f1_max_index = np.argmax(f1_scores[np.isfinite(f1_scores)])
`
where `f1_max` represents the F1-max score, and `thresholds[f1_max_index]` is the corresponding optimal threshold.

**Comment by archyin** [comment]
> Hi! You can binarize the anomaly map by selecting a threshold. I recommend using the optimal threshold obtained when calculating the F1-max score:
> 
> ```
> precisions, recalls, thresholds = precision_recall_curve(label, predict)
> f1_scores = (2 * precisions * recalls) / (precisions + recalls)
> f1_max = np.max(f1_scores[np.isfinite(f1_scores)])
> f1_max_index = np.argmax(f1_scores[np.isfinite(f1_scores)])
> ```
> 
> where `f1_max` represents the F1-max score, and `thresholds[f1_max_index]` is the corresponding optimal threshold.

每类图像集用同一个阈值吗？

**Comment by ByChelsea** [comment]
Yes, this is a viable approach.

**Comment by archyin** [comment]
> Hi! You can binarize the anomaly map by selecting a threshold. I recommend using the optimal threshold obtained when calculating the F1-max score:
> 
> ```
> precisions, recalls, thresholds = precision_recall_curve(label, predict)
> f1_scores = (2 * precisions * recalls) / (precisions + recalls)
> f1_max = np.max(f1_scores[np.isfinite(f1_scores)])
> f1_max_index = np.argmax(f1_scores[np.isfinite(f1_scores)])
> ```
> 
> where `f1_max` represents the F1-max score, and `thresholds[f1_max_index]` is the corresponding optimal threshold.
