### ISSUE TITLE
/data/visa/meta.json

### ISSUE THREAD

**Issue by abdalluhahmed** [ByChelsea/VAND-APRIL-GAN#8]
I hope this message finds you well. I've been working with your code for the Visa and MVTec datasets, and I've encountered an issue related to the missing meta.json file in the dataset path /data/visa/meta.json.

It seems that the code relies on this meta.json file to load important dataset information, and as a result, I'm encountering a FileNotFoundError when trying to run the code. The code snippet that specifically references the missing file is as follows:

meta_info = json.load(open(f'{self.root}/meta.json', 'r'))

I have checked the provided dataset path, and indeed, there is no meta.json file located at /data/visa/meta.json.

Could you please provide more guidance on how to resolve this issue? Do I need to create or obtain the meta.json file for the dataset, and if so, how should it be structured?

Your assistance in resolving this issue would be greatly appreciated. Thank you for your time and support.

Best regards,

**Comment by ByChelsea** [comment]
Hi! You can generate `meta.json` by following the instructions in [`README.md`](https://github.com/ByChelsea/VAND-APRIL-GAN#dataset-preparation)
