### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: 

### ISSUE THREAD

**Issue by cclamd** [ByChelsea/VAND-APRIL-GAN#9]
when run ` !python /content/VAND-APRIL-GAN/train.py --train_data_path "/content/VAND-APRIL-GAN/data" --config_path "/content/VAND-APRIL-GAN/open_clip/model_configs/ViT-B-16.json" `  it shows this error!

/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py:200: UserWarning: Error detected in LinalgVectorNormBackward0. No forward pass information available. Enable detect anomaly during forward pass for more information. (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:92.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/content/VAND-APRIL-GAN/train.py", line 176, in <module>
    train(args)
  File "/content/VAND-APRIL-GAN/train.py", line 140, in train
    loss.backward()
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [1, 196, 512]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by nuclearliu** [comment]
I have the same issue here

**Comment by tangyz213** [comment]
Could you teach me how to resolve this problem？

**Comment by oylz** [comment]
fix, change this [line](https://github.com/ByChelsea/VAND-APRIL-GAN/blob/master/train.py#L122) from 
```
patch_tokens[layer] /= patch_tokens[layer].norm(dim=-1, keepdim=True)
```
to:
```
patch_tokens[layer] = patch_tokens[layer]/patch_tokens[layer].norm(dim=-1, keepdim=True)
```
